services:
  - type: web
    name: whale-requirements-engineering
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=AutoTestGen_MAPS gunicorn app:app --chdir AutoTestGen_MAPS
    envVars:
      - key: SECRET_KEY
        generateValue: true 