services:
  - type: web
    name: whale-requirements-engineering
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python AutoTestGen_MAPS/app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true 