services:
  - type: web
    name: whale-requirements-engineering
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. gunicorn -w 4 -b 0.0.0.0:10000 app:app --chdir AutoTestGen_MAPS
    envVars:
      - key: SECRET_KEY
        generateValue: true 